name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dosyaları FTP ile yükle
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.termoland.com.tr
          username: u2626782@termoland.com.tr
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            hesaplayici/**